# Generated by Django 4.2.1 on 2023-06-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_in_kitchen_plan',
            field=models.BooleanField(default=False),
        ),
    ]
